version: '3.8'

services:
  app:
    container_name: auth
    build: ./
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - db
    networks:
      - auth

  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth
      - POSTGRES_HOST=localhost
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - auth

volumes:
  database_postgres:

networks:
  auth:
    driver: bridge